file(GLOB_RECURSE MEG_SOURCES CONFIGURE_DEPENDS "src/*.c" "include/*.h")
add_executable(meg ${MEG_SOURCES})
target_link_libraries(meg PUBLIC meglang)
target_include_directories(meg PUBLIC ${CMAKE_SOURCE_DIR}/targets/meglang/include)
if(MSVC)
  target_compile_options(meg PRIVATE /W4)
  target_compile_definitions(meg PRIVATE _CRT_SECURE_NO_WARNINGS)
else()
  target_compile_options(meg PRIVATE -Wall -Wextra -Wpedantic)
endif()